//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIRAFolderOpener.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JIRAFolderOpener.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No JIRA case found.
        /// </summary>
        internal static string Error_No_Case_Found {
            get {
                return ResourceManager.GetString("Error_No_Case_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected files to local folder.
        /// </summary>
        internal static string Txt_Btn_Start_Tooltip {
            get {
                return ResourceManager.GetString("Txt_Btn_Start_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode the selected files after unzipped.
        /// </summary>
        internal static string Txt_Decode {
            get {
                return ResourceManager.GetString("Txt_Decode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has selected {0} files.
        /// </summary>
        internal static string Txt_File_Count {
            get {
                return ResourceManager.GetString("Txt_File_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Selected.
        /// </summary>
        internal static string Txt_File_No_File {
            get {
                return ResourceManager.GetString("Txt_File_No_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        internal static string Txt_File_Refreshing {
            get {
                return ResourceManager.GetString("Txt_File_Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloaded All Files.
        /// </summary>
        internal static string Txt_File_Updated {
            get {
                return ResourceManager.GetString("Txt_File_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Folder.
        /// </summary>
        internal static string Txt_Switch_Local {
            get {
                return ResourceManager.GetString("Txt_Switch_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Txt_Switch_Server {
            get {
                return ResourceManager.GetString("Txt_Switch_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzip the selected files after copied to local folder.
        /// </summary>
        internal static string Txt_Unzip {
            get {
                return ResourceManager.GetString("Txt_Unzip", resourceCulture);
            }
        }
    }
}
